### ISSUE TITLE
New parent POM missing?

### ISSUE THREAD

**Issue by andi-huber** [openefsa/catalogue-browser#5]
Where do I find the parent POM for this project?

```xml
	<parent>
		<groupId>openefsa</groupId>
		<artifactId>all-projects</artifactId>
		<version>${global.version}</version>
	</parent>
```

**Comment by andi-huber** [comment]
Little remark: 

It would be much easier to work with the openefsa projects, if these could be restructured to have one top-level project/folder with the parent-pom and then have sub-folders with their own POMs for each of the currently existing projects (catalogue-browser, ...).

I believe this is best practice for larger projects when using maven anyway.

**Comment by AlbanShahajEFSA** [comment]
The parent pom.xml file has been updated and can be found here https://github.com/openefsa/catalogue-browser/blob/master/README.md

**Comment by AlbanShahajEFSA** [comment]
The publication of parent with all related modules is currently not done since many modules are used not only from the CB but also from other software. In any case excpect future updates since it may be that the structure will change and be easier to import.

**Comment by andi-huber** [comment]
Great to hear thx!

**Comment by AlbanShahajEFSA** [comment]
Thanks to you for the useful feedback.
