### ISSUE TITLE
Access to FoodEx2 Matrix through another software

### ISSUE THREAD

**Issue by LuciaSegovia** [openefsa/catalogue-browser#6]
Hi there, 

Would it be possible to access the matrix of FoodEx2 and use it with another open source software, like R?

Thanks!

Lucia

**Comment by AlbSha** [comment]
Hi Lucia,

it is possible to extract the MTX FoodEx2 Matrix catalogue directly from the Catalogue browser in a xlsx format that can be opened with Excel (check the "Tools" button on the main menu).

More than welcome,
Alban

**Comment by LuciaSegovia** [comment]
Hi Alban, 

I figured out! Thanks!

Lucia
